### ISSUE TITLE
missing parent_id field

### ISSUE THREAD

**Issue by foreverglory** [kevintweber/KtwDatabaseMenuBundle#13]
create my entity extends kevintweber\KtwDatabaseMenuBundle\Entity\MenuItem,
"php app/console doctrine:schema:update --force", missing parent_id field

**Comment by kevintweber** [comment]
You didn't give me much to go on here, so I can't give you much help.  I can hopefully direct you in the correct direction.  The "parent_id" is the name of the MenuItem::$parent field.

See https://github.com/kevintweber/KtwDatabaseMenuBundle/blob/ed6fa67c8b38ee0fe2f4bbcec63eb77407149c0c/Entity/MenuItem.php#L90

Perhaps this can get you going in the right direction.   - Kevin

**Comment by kevintweber** [comment]
Closing
