### ISSUE TITLE
Error ordering items

### ISSUE THREAD

**Issue by webs86** [kevintweber/KtwDatabaseMenuBundle#14]
I have tried bundle with mysql and postgresql. With MySQL seems not have problems, but with postgresql items are shown reversed.

Example: at [this gist](https://gist.github.com/webs86/dd0bc06c757b6044cee0) you can view example fixture.
With mysql I view:
- Home
- Page 1
- Page 2

With postgresql
- Page 2
- Page 1
- Home

I think entity need a field for sorting the items and use it during the select query.

**Comment by kevintweber** [comment]
@webs86 Can you please update the link to the gist.  I get a 404 error page.

**Comment by webs86** [comment]
@kevintweber Hi, I have update the to the gist

**Comment by kevintweber** [comment]
@webs86  Thanks for your quick update.

I see the issue that you are having.  Your idea of adding an order field for sorting is good, but adds a fair amount of complexity.  I will think about a solution to this issue, and (hopefully) commit a solution soon.

In the meantime, a perfectly good workaround is:
```php
// Retrieve "root" menuItem from the database.
$rootMenuItem = $entityManager
    ->getRepository('kevintweber\KtwDatabaseMenuBundle\Entity\MenuItem')
    ->getMenuItemByName('root');

// Reorder the children.  Line 489 of Entity/MenuItem.php
$rootMenuItem->reorderChildren(array(
    'Home',
    'Page 1',
    'Page 2'
));
```

I hope this helps.  - Kevin

**Comment by kevintweber** [comment]
Closing
