### ISSUE TITLE
CRUD

### ISSUE THREAD

**Issue by bogdaniel** [kevintweber/KtwDatabaseMenuBundle#15]
Can someone provide a crud example for this bundle ?:D. i'm trying to figure how to do it but .. out of luck

**Comment by kevintweber** [comment]
First, be sure that you have read: https://github.com/kevintweber/KtwDatabaseMenuBundle/blob/master/Resources/doc/index.md#usage

This bundle is designed to function pretty much the same as a KNP Menu, except that after the menu is set up you must persist it.

Rendering the menu is identical as with KNP Menu Bundle.

I hope this helps.  - Kevin
